### PR TITLE
Added symbol handling for numerators

### PR DESCRIPTION
**Pull request by kaapos**
Added the detection of symbolic expressions (excluding functions) in numerators. These symbols are now included in the `FORM` header files.

### CODE REVIEW

**Review by ValentinHirschi — CHANGES_REQUESTED** [review]
Thank you for this PR Kaapo!

There were a couple of small things I fixed already:

a) I now disable by default the numerator check.
b) When there is no additional symbols, the resulting syntax in FORM is `Auto ;` which is not admissible.
c) Depending on the outcome of the tensor integral reduction, you may have the d-dimensional "ε" symbol left, which is already independently handled through substitution. It needed to be filtered out.

This can be revealed by running my tests (with the slowest one disabled by default) with:

`cargo test --release`

And it's also good to add a new test for that numerator with additional symbols, which is what I did in `/tests/integral_evaluation_analytic_tests.rs` with name `test_integrate_3l_rank_4_additional_symbols_numerator`. You can run it independently of the others, with e.g. (also showcasing other options):

`RUST_BACKTRACE=full VAKINT_NO_CLEAN_TMP_DIR=T RUST_LOG=DEBUG cargo test --release --package vakint --no-default-features --no-fail-fast --test integral_evaluation_analytic_tests -- test_integrate_3l_rank_4_additional_symbols_numerator --exact --nocapture`

One remaining point is verifying that this numerator with additional symbols works with `MATAD` and `FMFT` as well (and perhaps `pySecDec` too, but if not easy, then at least return an error if additional symbols are detected).

Could I ask you to try and add this too for these evaluation modes, with the corresponding tests?

**Comment by kaapos** [comment]
Thanks for fixing the issues in the PR and for providing tips on next steps!

I've made the following updates:
1. Added support for additional symbols when using `MATAD` and `FMFT`.
2. Introduced two new tests in `/tests/integral_evaluation_analytic_tests.rs`:
    - `test_integrate_3l_rank_4_matad_additional_symbols_numerator` 
    -  `test_integrate_4l_h_rank_4_additional_symbols_numerator`
3. Added an error for detected additional symbols when using `pySecDec`.
4. Verified that all tests pass (didn't check the slow ones that are ignored by default).

Implementing the same functionality for `pySecDec` mode appears more involved, so I decided to leave it for the future.

Let me know if you encounter any issues with these commits!

**Review by ValentinHirschi — APPROVED** [review]
Thanks for this.

I may have to re-factor the code a bit so as to avoid code duplication between alphaloop, matad and FMFT handling, but ok, not urgent for now.

Also, I think it is actually easy to also support additional support in the numerator for `pySecDec`, i.e. we can handle it in the same way as I would for additional internal loop masses.
So this is what I did in my last push, and you can test this by running the `pySecDec` test `test_integrate_1l_cross_product_with_additional_symbols_numerator` from `integral_evaluation_pysecdec_tests.rs`, and you'll see that if you run `python3 run_pySecDec.py --help` from within the folder `./tests_workspace/test_integrate_1l_cross_product_additional_symbols_numerator` generator you get:

```
[...]
  --masses MASSES       Specify numerical values of masses (sorted in alphabetical order of their name) in Python-formatted list. (default: [1e0 #muvsq ,3e0 #A ,4e0 #B ]).[...]
```

Confirming how these parameters can be provided at run-time, but also with default values supplied in:
```
pub struct PySecDecOptions {
    [...]
    pub numerical_masses: HashMap<String, f64>,
    [...]
}
```

which can be supplied when building the `EvaluationMethod` of `PySecDec` to be supplied to `Vakint`'s evaluation stack when first instantiating it.

Can you give a quick try to that `PySecDec` test `test_integrate_1l_cross_product_with_additional_symbols_numerator` and make sure it goest through on your end as well?

**Comment by kaapos** [comment]
Thanks for the push! It's nice that it turned out to be easy to add the support for additional symbols in the numerator for `pySecDec` as well. It makes sense to to utilize the existing treatment for internal masses for the these extra symbols as well.

I ran the new test `test_integrate_1l_cross_product_with_additional_symbols_numerator` and it went through fine.

**Pull request merged**
